In [1]:
# Without Numpy
nums_list = [1,2,3,4,5]

result_num = [1,2,3,4,5]*5

result = []

for num in nums_list:
    result.append(num*5)

num
print('result',result)
print(result_num)

result [5, 10, 15, 20, 25]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [2]:
type(result)

list

In [3]:
# WIth Numpy

import numpy as np

arr = np.array([2,4,5,3,8])

np_result = arr*5

print(np_result)


[10 20 25 15 40]


In [4]:
type(arr)

numpy.ndarray

In [5]:
c = [0,2,5,10,15,20]
f = []

for i in c:
    f.append(i*1.8 + 32)

print(f)

[32.0, 35.6, 41.0, 50.0, 59.0, 68.0]


In [6]:
arr = np.array([0,2,5,10,15,20])

f = arr * 1.8 + 32
print(f)

[32.  35.6 41.  50.  59.  68. ]


In [7]:
a = [1,2,3,4,5]

b = [2,3,4,5,6]

In [8]:
range(len(a))

range(0, 5)

In [9]:
result = []

for i in range(len(a)):
    result.append(a[i] + b[i])

print(result)

[3, 5, 7, 9, 11]


In [10]:
# By using Numpy
import numpy as np


In [11]:
new_a = np.array(a)
new_b = np.array(b)

In [12]:
type(a)

list

In [13]:
add_arr = new_a + new_b
print(add_arr)

[ 3  5  7  9 11]


In [14]:
array_zero = np.zeros((3,4))

In [15]:
print(array_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
array_one = np.ones((3,4))

In [17]:
print(array_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
array_full = np.full((2,2),10)

In [19]:
array_full

array([[10, 10],
       [10, 10]])

In [20]:
arr = np.array([10,10,10,10])


In [21]:
arr.shape

(4,)

In [22]:
my_arr = np.arange(1,10,2)

In [23]:
type(my_arr)

numpy.ndarray

In [24]:
my_lst = list(range(1,10,2))

In [25]:
type(my_lst)

list

In [26]:
np.linspace(1,10,2)

array([ 1., 10.])

In [27]:
# Generate Numpy Random numbers
np.random.rand()

0.6275179447226733

In [28]:
np.random.rand(4,5)


array([[0.98001476, 0.61516179, 0.49544387, 0.77515815, 0.7606775 ],
       [0.69370046, 0.29746227, 0.40816971, 0.18356233, 0.13203938],
       [0.01812233, 0.52187475, 0.17272566, 0.94717815, 0.30029402],
       [0.93317139, 0.44854565, 0.85124592, 0.80922084, 0.29372905]])