<a href="https://colab.research.google.com/github/aakashkumar089/Class-notes/blob/main/OTS_Numpy_class1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Without Numpy
nums_list = [1,2,3,4,5]

result_num = [1,2,3,4,5]*5

result = []

for num in nums_list:
    result.append(num*5)

num
print('result',result)
print(result_num)

result [5, 10, 15, 20, 25]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [2]:
type(result)

list

In [3]:
# WIth Numpy

import numpy as np

arr = np.array([2,4,5,3,8])

np_result = arr*5

print(np_result)


[10 20 25 15 40]


In [4]:
type(arr)

numpy.ndarray

In [5]:
c = [0,2,5,10,15,20]
f = []

for i in c:
    f.append(i*1.8 + 32)

print(f)

[32.0, 35.6, 41.0, 50.0, 59.0, 68.0]


In [6]:
arr = np.array([0,2,5,10,15,20])

f = arr * 1.8 + 32
print(f)

[32.  35.6 41.  50.  59.  68. ]


In [7]:
a = [1,2,3,4,5]

b = [2,3,4,5,6]

In [37]:
a+b

[1, 2, 3, 4, 5, 2, 3, 4, 5, 6]

In [8]:
range(len(a))

range(0, 5)

In [9]:
result = []

for i in range(len(a)):
    result.append(a[i] + b[i])

print(result)

[3, 5, 7, 9, 11]


In [10]:
# By using Numpy
import numpy as np


In [11]:
new_a = np.array(a)
new_b = np.array(b)

In [12]:
type(a)

list

In [13]:
add_arr = new_a + new_b
print(add_arr)

[ 3  5  7  9 11]


In [14]:
array_zero = np.zeros((3,4))

In [15]:
print(array_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
array_one = np.ones((3,4))

In [17]:
print(array_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
array_full = np.full((2,2),10)

In [19]:
array_full

array([[10, 10],
       [10, 10]])

In [20]:
arr = np.array([10,10,10,10])


In [21]:
arr.shape

(4,)

In [33]:
my_arr = np.arange(1,11,3)

In [34]:
print(my_arr)

[ 1  4  7 10]


In [35]:
type(my_arr)

numpy.ndarray

In [24]:
my_lst = list(range(1,10,2))

In [36]:
my_lst

[1, 3, 5, 7, 9]

In [25]:
type(my_lst)

list

In [29]:
np.linspace(1,10,2)

array([ 1., 10.])

In [27]:
# Generate Numpy Random numbers
np.random.rand()

0.6275179447226733

In [58]:
my_random_arr= np.random.rand(4,5)


In [42]:
# Product

print(new_a)
type(new_a)

[1 2 3 4 5]


numpy.ndarray

In [43]:
print(new_b)

[2 3 4 5 6]


In [44]:
type(new_b)

numpy.ndarray

In [47]:
inner_prod = np.inner(new_a,new_b)

In [48]:
print(inner_prod)

70


In [53]:
outer_prod = np.outer(new_a,new_b)

In [54]:
print(outer_prod)

[[ 2  3  4  5  6]
 [ 4  6  8 10 12]
 [ 6  9 12 15 18]
 [ 8 12 16 20 24]
 [10 15 20 25 30]]


In [56]:
outer_prod.shape

(5, 5)

In [57]:
array([[  0,   1,   2,   3,   4],
   [-99,   6, -99,   8, -99],
    [-99,  11, -99,  13, -99]])

NameError: name 'array' is not defined

In [59]:
my_random_arr.shape

(4, 5)

In [65]:
x = np.arange(15).reshape(5,3)

In [68]:
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [69]:
type(x)

numpy.ndarray

In [92]:
x[1:,::]

array([3, 4, 5])